### ISSUE TITLE
skip_strings configuration format / support for global and file-specific matches

### ISSUE THREAD

**Issue by mykter** [feeltheajf/trufflehog3#15]
Hi, thanks for the tool, love the non-git option compared to the original.

I've tried to use skip_strings to ignore some strings wherever they appear, and some in only certain files, like this:
```yaml
skip_strings:
  - "enc[aes256_gcm,data" # sops encrypted data in any file
  - "data:image/png;base64,"
  - sflkxwrjsmekkf2qt4fwpmejf36pok6yjv_adqssw5c # example jwt sig from jwt.io
  - ui/index.html:
      - apikey
```
However I get this error:
```
Traceback (most recent call last):
  File "/home/mmacnair/.local/bin/trufflehog3", line 8, in <module>
    sys.exit(run())
  File "/home/mmacnair/.local/lib/python3.8/site-packages/truffleHog3/cli.py", line 51, in run
    issues.extend(scan(tmp, config, rules))
  File "/home/mmacnair/.local/lib/python3.8/site-packages/truffleHog3/cli.py", line 99, in scan
    issues.extend(engine.process(meta))
  File "/home/mmacnair/.local/lib/python3.8/site-packages/truffleHog3/lib/search.py", line 51, in process
    if self.should_skip(match, line, issue["path"]):
  File "/home/mmacnair/.local/lib/python3.8/site-packages/truffleHog3/lib/search.py", line 65, in should_skip
    if line.find(s) >= 0:
TypeError: must be str, not dict
```
The config file in the repo suggests that it does support a dict-like option, but is it all-or nothing, you can't have both? If so, feature request: can we have both?

**Comment by feeltheajf** [comment]
Hi @mykter

I appreciate your kind words! 

There's no support for both, but you can specify "/" key to skip strings in all files, like in [examples/trufflehog.yaml](https://github.com/feeltheajf/trufflehog3/blob/2.x/examples/trufflehog.yaml).

**Comment by mykter** [comment]
ah I see thanks, I didn't notice the examples dir.
