### ISSUE TITLE
Trufflehog3 can't work with bare repositories

### ISSUE THREAD

**Issue by archi144** [feeltheajf/trufflehog3#31]
Hello!
When I try to scan bare repositry (`git clone --bare`) I've got:
```
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog3", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/trufflehog3/cli.py", line 72, in run
    issues.extend(scan(target, config, rules, args.processes))
  File "/usr/local/lib/python3.10/site-packages/trufflehog3/core.py", line 53, in scan
    files.extend(
  File "/usr/local/lib/python3.10/site-packages/trufflehog3/source.py", line 104, in gititer
    for branch in _get_branches(repo, branch):
  File "/usr/local/lib/python3.10/site-packages/trufflehog3/source.py", line 208, in _get_branches
    return repo.remotes.origin.fetch(branch)
  File "/usr/local/lib/python3.10/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.10/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'. 
```
Is this expected behaviour? 
Thanks in advance!

P.S. [truffleHog](https://github.com/trufflesecurity/truffleHog) works fine with bare repositories

**Comment by feeltheajf** [comment]
Hey @archi144 

Good catch! This should be fixed in v3.0.3
