### ISSUE TITLE
trufflehog3 requires pyyaml==5.4.1 which has cython related compilation issues

### ISSUE THREAD

**Issue by devinleighsmith** [feeltheajf/trufflehog3#50]
pyyaml 5.4.1 has cython related failures during build: https://github.com/yaml/pyyaml/issues/724

I was able to manually resolving this with no-deps and using pyyaml 6.0.0

would it be possible to bump the requirements to pyyaml==6.0.0 or pyyaml>=5.4.1 ?

**steps to reproduce:**

pip install trufflehog3

**expected result:**

installs trufflehog

**actual result:**

```pip install trufflehog3
Collecting trufflehog3
  Using cached trufflehog3-3.0.6-py2.py3-none-any.whl (34 kB)
Requirement already satisfied: attrs==20.3.0 in c:\users\devins\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trufflehog3) (20.3.0)
Requirement already satisfied: GitPython==3.1.30 in c:\users\devins\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trufflehog3) (3.1.30)
Requirement already satisfied: Jinja2==3.0.1 in c:\users\devins\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from trufflehog3) (3.0.1)
Collecting PyYAML==5.4.1 (from trufflehog3)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 314, in run
          self.find_sources()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 322, in find_sources
          mm.run()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\command\sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\DevinS\AppData\Local\Temp\pip-build-env-za4cr10g\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by OsamaMahmood** [comment]
@devinleighsmith i tried using this no-deps way around in gitlab ci but it is still failing the installation

**Comment by feeltheajf** [comment]
Hi @OsamaMahmood 
Please check [v3.0.7](https://pypi.org/project/trufflehog3/3.0.7/). See also [pyyaml#724](https://github.com/yaml/pyyaml/issues/724)

**Comment by devinleighsmith** [comment]
Thanks!
